### PR TITLE
Maintenance

### LINKED ISSUE #7: Tests fail on node 13
```
✖ request                                      
inequivalent (/node_modules/fluture/test/assertions.js:55:18)
assertInnerEqual (/node_modules/fluture/test/assertions.js:47:15)
/node_modules/fluture/test/assertions.js:76:28
Computation$rej$cont (/node_modules/fluture/src/future.js:150:9)
Computation$rej (/node_modules/fluture/src/future.js:153:9)
/index.js:290:36
internal/util.js:392:14
finish (internal/streams/pipeline.js:174:7)
internal/streams/pipeline.js:180:7
internal/util.js:392:14

    chain (body => {
  const location = new URL (url);
  const makeRequest = lib => Future ((rej, res) => {
    const req = lib.request (location, options);
    req.once ('response', res);
    pipeline (body, req, e => e && rej (e));
    return () => {
      req.removeListener ('response', res);
      req.abort ();
    };
  });
  return chain (makeRequest) (getRequestModule (location.protocol));
}) (encase (buf => new Readable ({
  highWaterMark: buf.byteLength,
  read: function() {
    if (this._pushed || this.push (buf)) { this.push (null); }
    this._pushed = true;
  },
})) ()) :: Future({ <rejected> new Error ("connect ECONNREFUSED 127.0.0.1:443") })
    is not equivalent to:
    reject (new Error ("connect ECONNREFUSED 127.0.0.1:443")) :: Future({ <rejected> new Error ("connect ECONNREFUSED 127.0.0.1:443") })

The inner values are not equal: Expected values to be strictly deep-equal:
+ actual - expected

  [Error: connect ECONNREFUSED 127.0.0.1:443] {
    address: '127.0.0.1',
    code: 'ECONNREFUSED',
+   errno: -111,
-   errno: 'ECONNREFUSED',
    port: 443,
    syscall: 'connect'
  }
```

### PR DESCRIPTION
**Pull request by Avaq**
Closes #7

### CODE REVIEW

File: test/index.js [hunk 1]
```diff
@@ -231,15 +231,15 @@ test ('acceptStatus', () => Promise.all ([
...
+test ('responseToError', () => (
+  assertRejects (fl.chain (fn.responseToError) (mockResponse ({code: 500, message: 'Internal Server Error', headers: responseHeaders})
+                                                             (Buffer.from ('Dear user,\n\nEverything broke down.\nWe are sorry.'))))
                  (new Error (
                    'Unexpected Internal Server Error (500) response. Response body:\n' +
                    '\n' +
                    '  Dear user,\n' +
                    '  \n' +
                    '  Everything broke down.\n' +
                    '  We are sorry.'
```
Comment (davidchambers) [inline test/index.js]: :arrow_left:

Comment (Avaq) [reply test/index.js]: Ah, yes. Thanks.

**Review by dicearr — APPROVED** [review]
